[[CImGui]]
arch = "aarch64"
git-tree-sha1 = "072222afadee9f81b38a0329336b58301d8cb402"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "e15b7886cdaf292f5c373cf84a78730f76ba8ecd978e35228dea57ec1a4f7200"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.78.0+0/CImGui.v1.78.0.aarch64-linux-gnu.tar.gz"
[[CImGui]]
arch = "aarch64"
git-tree-sha1 = "277f06b457021ac3eebeb45799f66216ffc7a6cc"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "475d6fa822771091c88aa6cfe3e5ab026c28f74b61f1dd31e043d161e23b1377"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.78.0+0/CImGui.v1.78.0.aarch64-linux-musl.tar.gz"
[[CImGui]]
arch = "armv7l"
git-tree-sha1 = "a27996f9a22db68ad2e94a4e4d598419874b63a6"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "2cb827ede56933080e54b4d8c3a0725091f1bb1e0c3148a0ea06bf8da59bec3f"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.78.0+0/CImGui.v1.78.0.armv7l-linux-gnueabihf.tar.gz"
[[CImGui]]
arch = "armv7l"
git-tree-sha1 = "dd0a03f4b5dae4902adf7478fb4dfe3fb10a14d1"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "cb81a71f0c7bc6e8f3987479b3b53595e821c26614c6659440f6f3f65b247c19"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.78.0+0/CImGui.v1.78.0.armv7l-linux-musleabihf.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "c64e3baf3c17d23407799c6cd2124a02bada6423"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "0bcff6da0df6764da0e02a5470d553c1b8d3c5d68761d9a091ed71a20059f8eb"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.78.0+0/CImGui.v1.78.0.i686-linux-gnu.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "855278b56209a7fe516f8c4ebe77a76d8ad435ea"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "15b75590da4863d8c108f3774859d276a8826ec3e03fd55d11c10c0c9050f250"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.78.0+0/CImGui.v1.78.0.i686-linux-musl.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "c49e4055c225aa877e9b20bfee2d7fcdbfca8eea"
os = "windows"

    [[CImGui.download]]
    sha256 = "3db15d9590fa95a128e0057ebf8c73e0a9ea4561ea4abf4916667a269e027449"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.78.0+0/CImGui.v1.78.0.i686-w64-mingw32.tar.gz"
[[CImGui]]
arch = "powerpc64le"
git-tree-sha1 = "7f9e5569e2ff8a837215e8dfa28a8d4a5f264958"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "08d41d179df31b47b9a1f0bb7f9fec09b2a765f91cf6b45635eddc94d8bf5fdd"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.78.0+0/CImGui.v1.78.0.powerpc64le-linux-gnu.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "0dbeeca1ac209cd1bf708c95da8d33423d95dad8"
os = "macos"

    [[CImGui.download]]
    sha256 = "c2a4fb32a8fb80d3b3422d6ecee023dd67ab10219280c0ccc6f4a0b72f99bbf9"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.78.0+0/CImGui.v1.78.0.x86_64-apple-darwin14.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "89767ab8e58ff81d6deb6d91e0eaa412009963f4"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "afff0be634520fbecc2f85177c1b6db634653ca0d009262a0b4d644015f7cb78"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.78.0+0/CImGui.v1.78.0.x86_64-linux-gnu.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "5ed0a6cb5d7f8a75ed1b589047d3c40510dba38d"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "ac15a01062278259411e3fc7ffa1c94119d147a46fc052fbc89794c3b5ed09d3"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.78.0+0/CImGui.v1.78.0.x86_64-linux-musl.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "013b69c8f022830cc9d99cac96eb2b4a7a8ce54d"
os = "freebsd"

    [[CImGui.download]]
    sha256 = "96859cc8cb2848e9ee0ef1cb030038acf375b715824553f0a9b739c6b04dff79"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.78.0+0/CImGui.v1.78.0.x86_64-unknown-freebsd11.1.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "d47e9affaed6dd0e59dff721ebb86dd8347b057f"
os = "windows"

    [[CImGui.download]]
    sha256 = "95a11e073719dee4cc99abb55cae3a63cf3e8e46cf6e73504dc7dd8098ea63b5"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.78.0+0/CImGui.v1.78.0.x86_64-w64-mingw32.tar.gz"
