[[CImGui]]
arch = "aarch64"
git-tree-sha1 = "b5cbae1bbbfdce94927bd4faf535244fe565168e"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "55275ce51246c151b777c5a746d8f530fab93e6585ec7b78d0e6c5df03f8c64c"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.82.0+0/CImGui.v1.82.0.aarch64-linux-gnu.tar.gz"
[[CImGui]]
arch = "aarch64"
git-tree-sha1 = "88169ca6702b5993c1fa1d340a5aa5542b1e0bf3"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "0bbfc30ae8359b9e33643d11f9cf05e9563101357e2df5863c4bbd9599f66382"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.82.0+0/CImGui.v1.82.0.aarch64-linux-musl.tar.gz"
[[CImGui]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cc509a9b10d9ebeb7e2c0694f55fc6951505aae7"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "8eeed63ff0dfdb63d2475da62c52ad7b8c5f4ac2e52fe2eeaab223dd088ea227"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.82.0+0/CImGui.v1.82.0.armv7l-linux-gnueabihf.tar.gz"
[[CImGui]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "81e66abb02c98231513f065a293c31655a991242"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "e06f5f93587b52959b27481a2f9bea5513473bfcab583c001eabcdd4a00c163b"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.82.0+0/CImGui.v1.82.0.armv7l-linux-musleabihf.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "e0b08f532b7f30a953c82944fabe4f41e3b81659"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "6e15c48c0f5cd56d363d1125387824894a6737ed9e0db6a214f81404f52e0e3b"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.82.0+0/CImGui.v1.82.0.i686-linux-gnu.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "3f692c7ffd17fc0d1963aef5dec4c3eb9074ba26"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "1605e9e8e003d99a562ecdfa96b4fa87f45f3a992acd7b005430b6d7875caad7"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.82.0+0/CImGui.v1.82.0.i686-linux-musl.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "af5197af34174b502e49a362336443e63a76f4b7"
os = "windows"

    [[CImGui.download]]
    sha256 = "e4e941875851192f633917e8ef2d73b4ce26000844eb1a5263715d4a58c948d7"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.82.0+0/CImGui.v1.82.0.i686-w64-mingw32.tar.gz"
[[CImGui]]
arch = "powerpc64le"
git-tree-sha1 = "845ffe1b2229265ae27ccc9b1e1fd9e013d824f6"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "675f667fec1fb1d6dd3ccce0c4e0eeff203b2515e48e78dd59adb2d2b01d3efe"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.82.0+0/CImGui.v1.82.0.powerpc64le-linux-gnu.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "c808fb33c88145d6d8cd5666fc192a49c09282d0"
os = "macos"

    [[CImGui.download]]
    sha256 = "79efd84459c91af4d5c6ed89f7b654ad2487e67671d811641e4406952a0d812e"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.82.0+0/CImGui.v1.82.0.x86_64-apple-darwin.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "208339502284000692b7ee177b74b31a4b2ee8ea"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "14b0aecc077231b680356a754b1daf204695ab426336b8c97b83070c1704ad77"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.82.0+0/CImGui.v1.82.0.x86_64-linux-gnu.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "66494981301e6edad221310788d29e2d3488226d"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "35998c96fed7d211b8288f017da5c719e43519dc3a86d4b0cf951ffdc1f1468d"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.82.0+0/CImGui.v1.82.0.x86_64-linux-musl.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "74a68a92421d24341d2999e4a55cd23f80ebdda5"
os = "freebsd"

    [[CImGui.download]]
    sha256 = "3e9df219cb12f7ac74291d8b7a4ffe864d25d1a1365e2b24d34b83f7d3152b79"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.82.0+0/CImGui.v1.82.0.x86_64-unknown-freebsd.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "8b1cbc5bf83fffa4b9032fbcb791e54ec290691c"
os = "windows"

    [[CImGui.download]]
    sha256 = "ff9081b09fdf27f7b59c8f8b675051b60445d3a20507616b0b35b60adab093ef"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.82.0+0/CImGui.v1.82.0.x86_64-w64-mingw32.tar.gz"
