[[CImGui]]
arch = "i686"
git-tree-sha1 = "b0fb685946ddbdce014bdc8b66eabeecccb98d1a"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "66134521a7ebc677a7f95f4875e1db0da2a3603e512978f6f32c4e19680fde75"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+1/CImGui.v1.75.0.i686-linux-musl.tar.gz"
[[CImGui]]
arch = "aarch64"
git-tree-sha1 = "d1afb52167e1f55c4670a61408f05da782d7296b"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "755cf5fd333d4e0d011c00dc1f383443cad0797009a0ffa8b024900df545a79a"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+1/CImGui.v1.75.0.aarch64-linux-musl.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "80ae91a0d51a826dfc55f2e1a5b11385ac40c18f"
os = "windows"

    [[CImGui.download]]
    sha256 = "5aa42188499a898b280641e82fe62a90c6e5d1e2ab33d6bf69395640c20220d8"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+1/CImGui.v1.75.0.i686-w64-mingw32.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "505d5ef5f4803fa353e426c48d65337a9039fb9b"
os = "windows"

    [[CImGui.download]]
    sha256 = "0f03f00bc06ad4f8c6d3128a4dfcbdee2e6c649b89d006e39e0677a26a5e9d17"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+1/CImGui.v1.75.0.x86_64-w64-mingw32.tar.gz"
[[CImGui]]
arch = "armv7l"
git-tree-sha1 = "8592c65e881900284853a6b27bedfad175fff3bc"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "92117763fb5d84f03e4e3a41148c373843a303d1a498382a20d2efae55507ad2"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+1/CImGui.v1.75.0.armv7l-linux-gnueabihf.tar.gz"
[[CImGui]]
arch = "armv7l"
git-tree-sha1 = "32a2d8ae6f9331d899a0f5ace80cd4b20fb8d195"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "2009740b37da8db513ba1fac2638d7a5d491a0c27c4c84182bd092b70f982cc6"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+1/CImGui.v1.75.0.armv7l-linux-musleabihf.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "fed37cfb812f7b5b649b028e624165fe6e793691"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "5804cd8ae7b01fd2155e72be9a74b0e9523f5b24ee9f8b84b841cff3bb671fdd"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+1/CImGui.v1.75.0.i686-linux-gnu.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "5902bb4f5488c57ebc100c8a137253d13fe2e7e2"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "cd8dc6ebccfb45346b0c7b07f025f5ed5417c0cab5eefa3e58e7efe7123bcdd7"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+1/CImGui.v1.75.0.x86_64-linux-gnu.tar.gz"
[[CImGui]]
arch = "powerpc64le"
git-tree-sha1 = "7ea7702328d03c973ca19df0d2fb70619bee305e"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "658623ea4948bd41bf8a4e65f7e8e47a7935ea7e71871d0e30b99150f3ce99e4"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+1/CImGui.v1.75.0.powerpc64le-linux-gnu.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "3a4446e28fe1f0cc651c0d8b60c7be19f061ea9b"
os = "macos"

    [[CImGui.download]]
    sha256 = "efb695ff8c5e77731d124b8d56f86759c07694b871c4faa22ecc61e345fd982b"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+1/CImGui.v1.75.0.x86_64-apple-darwin14.tar.gz"
[[CImGui]]
arch = "aarch64"
git-tree-sha1 = "8ebced55c720f1adf4418fc9e292c25b654606b2"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "b5b348aa01b2f294463853532a7895b47152a5d3ce948141ba3d65abe75cc0d5"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+1/CImGui.v1.75.0.aarch64-linux-gnu.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "434c62a3e837321fde43ecab8be99851b791946f"
os = "freebsd"

    [[CImGui.download]]
    sha256 = "e783bc21de27e1e3d8c900a454ba7877e10c26d7a5e6283dc2c796cd3858f0e5"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+1/CImGui.v1.75.0.x86_64-unknown-freebsd11.1.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "226286dbf3767e28c37e299d70622308d1b33bc3"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "6dc2d82ed9c25eec7e3421a8344993958934519df246a32887be5ace594eb151"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+1/CImGui.v1.75.0.x86_64-linux-musl.tar.gz"
