[[CImGui]]
arch = "aarch64"
git-tree-sha1 = "a392ebc994f154022a4e78eff31c6e6e29618b1f"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "384249e5d6ec7fabe55b2d05377e51bb4f194966eda6a89ba5ac54aff925c5c6"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.77.0+0/CImGui.v1.77.0.aarch64-linux-gnu.tar.gz"
[[CImGui]]
arch = "aarch64"
git-tree-sha1 = "198b0028396cd592cda1f8facc420e0202e39d1c"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "e10463cb248ed2563832a4dcf6426dafe62fd5979e7f42a47c084a04ff40877c"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.77.0+0/CImGui.v1.77.0.aarch64-linux-musl.tar.gz"
[[CImGui]]
arch = "armv7l"
git-tree-sha1 = "f0859325248bf7c2ec50724e950e5daaec6f65bd"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "55c7c6d458d4b5044945838b36c0672c48e238609f7baf461a337090bcc5bb18"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.77.0+0/CImGui.v1.77.0.armv7l-linux-gnueabihf.tar.gz"
[[CImGui]]
arch = "armv7l"
git-tree-sha1 = "e873c9b4f5783ed8c0ce67c845e7a7e8a87069ce"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "26de61f342a92b27cc8e5930bff6ce532166941468ffbaa6278a74eaedb12898"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.77.0+0/CImGui.v1.77.0.armv7l-linux-musleabihf.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "28ca0a699a4009af32401d68f4a7e6d72086ffc4"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "e87c624e86a92b35dfc3bc831c61263c7e95b58137bf0061b59887c9db29e49e"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.77.0+0/CImGui.v1.77.0.i686-linux-gnu.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "c4d5e99d59c90248c242ef7a3f8ec2312cb66532"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "681d3de7ce101e50e89ef612b3085a60fa6a32327e6dd285819578718c8243f6"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.77.0+0/CImGui.v1.77.0.i686-linux-musl.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "64cb8aadb74606473ed3d3a365c0c64d72094c27"
os = "windows"

    [[CImGui.download]]
    sha256 = "5fbefbde265130e362040a2972cfa9965b86a614c8a792645295265172512602"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.77.0+0/CImGui.v1.77.0.i686-w64-mingw32.tar.gz"
[[CImGui]]
arch = "powerpc64le"
git-tree-sha1 = "56ffa59378951524df5ba7e36a32c8c019f1224f"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "6e0755d386092cb66fe9e9a957d17c28fc9417aedb7dbb3259ae9fc2e06fd2c2"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.77.0+0/CImGui.v1.77.0.powerpc64le-linux-gnu.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "92a40032b0a3adc87587692c3324c255bb569f42"
os = "macos"

    [[CImGui.download]]
    sha256 = "268000c37beda5db651afd5e6d2f5695e8cbd14c86e5f8aa4fd2f9ee597987b4"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.77.0+0/CImGui.v1.77.0.x86_64-apple-darwin14.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "5fdf8d579573e724b2fbe994a29d113ca81b108e"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "1a1042c1daf7c4fc5a98d1f53980e6aa97a2aff3e35fa3d5a9b23f703a887f66"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.77.0+0/CImGui.v1.77.0.x86_64-linux-gnu.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "0422f7ae81fe5c7c0b8583d4b068d2127e97ee87"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "e0450e53c900f750dcc6d93b25cb942294237a93fe3f1f4ed145b61b6f92b93a"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.77.0+0/CImGui.v1.77.0.x86_64-linux-musl.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "b3d13362fc6556fe326c6658147f7a48462d741d"
os = "freebsd"

    [[CImGui.download]]
    sha256 = "7a5f2abeb811e8c2cadef012f58fb0e34a9ebcb16a2d5a5fd4f5bc0da54d1c8f"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.77.0+0/CImGui.v1.77.0.x86_64-unknown-freebsd11.1.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "5a5c1101cfb4653ca1dd335c2dbc0e0cefb7a3c2"
os = "windows"

    [[CImGui.download]]
    sha256 = "3f535aca4c4cab301000379c4bea7565f4705d7d44d9d4813e9ed5429a916ea3"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.77.0+0/CImGui.v1.77.0.x86_64-w64-mingw32.tar.gz"
