[[CImGui]]
arch = "i686"
git-tree-sha1 = "9f323f56f0cafe1f9528a4774e1a0974af6a2454"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "fb2d5032b7cfe37621c8e42321d0f62f33401bbdf7136d7412b7d9deb1d13f8a"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+0/CImGui.v1.76.0.i686-linux-musl.tar.gz"
[[CImGui]]
arch = "aarch64"
git-tree-sha1 = "c13c4e4044c14392368b9c07cedd5bb805b19718"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "17b31edec37cc6b48f5ffd2c90d458f1840d3cd178207e52c82cca532f89561e"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+0/CImGui.v1.76.0.aarch64-linux-musl.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "71582d6b86d9a0efdfb7bba5e505905d3c4f2f5e"
os = "windows"

    [[CImGui.download]]
    sha256 = "59b0cdcdb47d74320a10a311c9bb0832474e78f881dad6567428089a47125e67"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+0/CImGui.v1.76.0.i686-w64-mingw32.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "92b8fae2142e5adaad7a33de18011135a05748f3"
os = "windows"

    [[CImGui.download]]
    sha256 = "d4707e66f61272d18133776b0dd7d7e56109a46546b1820681b8167e2e86fe15"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+0/CImGui.v1.76.0.x86_64-w64-mingw32.tar.gz"
[[CImGui]]
arch = "armv7l"
git-tree-sha1 = "98f93430a9fd3e32dae29bad3cb0e7e1864bef78"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "628762c59992b135e92ec1aea0356d041381c6aa01ce2140ea10924b6a5117b5"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+0/CImGui.v1.76.0.armv7l-linux-gnueabihf.tar.gz"
[[CImGui]]
arch = "armv7l"
git-tree-sha1 = "de81046aecee83a4eb00ee5feb403474ea7626a0"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "c960b8265c8ccb9fa12f9c7a841969946c3aad0d19884de20e76f571530182a3"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+0/CImGui.v1.76.0.armv7l-linux-musleabihf.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "59b36e00ed4d57bbc12f948fc2449f8489531695"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "e4b13263d68b61f1efa568165e77fc361797dafecc287471e84e9b2409b517fd"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+0/CImGui.v1.76.0.i686-linux-gnu.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "5c0aefbd1086e59ea3504043f12ff87ed1f7d5d6"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "701a753324329958fcbed5724e045b5deb5751d994d98055bbed24d5ba43d0f9"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+0/CImGui.v1.76.0.x86_64-linux-gnu.tar.gz"
[[CImGui]]
arch = "powerpc64le"
git-tree-sha1 = "eacf911d9438e2fe0b937f114a600a4c6ec3296b"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "ef724b0b788c51306fece0abe0be160eb276723566bcb1d6ee3438fb9a895a9c"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+0/CImGui.v1.76.0.powerpc64le-linux-gnu.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "44e47e32882543e713219f986c327ea5becbf951"
os = "macos"

    [[CImGui.download]]
    sha256 = "adeb2110c446c008b9b0825890350a142e2f09de30941a1c222f18c8e3c471e5"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+0/CImGui.v1.76.0.x86_64-apple-darwin14.tar.gz"
[[CImGui]]
arch = "aarch64"
git-tree-sha1 = "3dc1e76a1d6c5ad6dfb38b4bedd1cf39df656a36"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "53671bbd828f521a99e88274f2022ef062c9d6d17dd4b6a4837c5f5fdc8d1f1e"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+0/CImGui.v1.76.0.aarch64-linux-gnu.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "a4ca8e834eba947de1ae1ea2b9bd4440505b7f79"
os = "freebsd"

    [[CImGui.download]]
    sha256 = "4fbf7d90059e136fdc7c2a056d546736b7bf4442e7c2b1bd2d9a99742840739d"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+0/CImGui.v1.76.0.x86_64-unknown-freebsd11.1.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "f4f62507f72bbcb3046c3c487ee2892f24c12beb"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "47ab2eabb0eb596cb64010797b6b958e122caa84af2514b96e339fa1de56669b"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+0/CImGui.v1.76.0.x86_64-linux-musl.tar.gz"
