[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "5a2ef1154f3c423388832e6940fdaa418f03d04d"
os = "freebsd"

    [[CImGui.download]]
    sha256 = "7e3efc2b68a356a1395343b25d628a2964ecc07571d73f0f55590023f05fe142"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+2/CImGui.v1.75.0.x86_64-unknown-freebsd11.1.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "753a6594c3e27a318950aef3c36c63a77c234f45"
os = "windows"

    [[CImGui.download]]
    sha256 = "af3e702236e5a5d714cb3858dddfeab9e6be0c913fa1cd4e431b5a13ab6b83a3"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+2/CImGui.v1.75.0.x86_64-w64-mingw32.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "a97c9b2d15db92784f98ee243941b635b12e6afd"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "02ec845d4e216d0397818304d522926444b587972fb9eea09d55fb230b98af58"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+2/CImGui.v1.75.0.x86_64-linux-gnu.tar.gz"
[[CImGui]]
arch = "armv7l"
git-tree-sha1 = "59ecae6c8015c6a933101eb8395e2edbd8847c1f"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "543af874de7bf80d7f7adf1c5333faadb088adb56cecce27c5a2a4bdf7777eff"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+2/CImGui.v1.75.0.armv7l-linux-musleabihf.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "efea454fbd5f61b64502dede677ab1fad58546b3"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "212c90460579a3ed15f1cbf99a5deca3fd185715198acba26972537c18b4739e"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+2/CImGui.v1.75.0.i686-linux-gnu.tar.gz"
[[CImGui]]
arch = "aarch64"
git-tree-sha1 = "9302dfc798c8800d88fb2fddb8a47966916913fd"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "1bfa60e13670fec9384316a6d1264ce76acb72256182758542ec8bd2f343485a"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+2/CImGui.v1.75.0.aarch64-linux-musl.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "4ea1c7ba16e7cb36523bd750d608523036c0205b"
os = "windows"

    [[CImGui.download]]
    sha256 = "4d3554d5246544ab16a26891c9ac0bf4b46ba42ec20a9071b4806c425c5afab4"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+2/CImGui.v1.75.0.i686-w64-mingw32.tar.gz"
[[CImGui]]
arch = "aarch64"
git-tree-sha1 = "63be6e7a84bbb5c39aa8cc2e3626a74fccc3ef7d"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "76eaf7bb18e9930169161c94ef05ea35e73044120151dba1fe051ad4cf345b2e"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+2/CImGui.v1.75.0.aarch64-linux-gnu.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "95cbe005374b6adfeb7067bbb283675355154f85"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "6768e5f3e7c10aae7e6d0a43bb0aa5e8fcdccbdaf52ff88ee46a8685cf8f5bf5"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+2/CImGui.v1.75.0.i686-linux-musl.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "da853cc9df89c44d38f96f71add8891a51d29818"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "37c94c6e55d2d124ef6e731d7b7ee409003e98d18239b08ecaa26ece3bda2f74"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+2/CImGui.v1.75.0.x86_64-linux-musl.tar.gz"
[[CImGui]]
arch = "powerpc64le"
git-tree-sha1 = "df86011ee5ddb7cf1938b88a7cde29201c2fc38b"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "cf25e32b63bedc36efa67aa12d58c221663312a0c26df42d5eac86645cecef09"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+2/CImGui.v1.75.0.powerpc64le-linux-gnu.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "16c4d35ee8a9344634aeda972dd5f170c8a120c1"
os = "macos"

    [[CImGui.download]]
    sha256 = "c44d64ca9395e13ea56452cf1f5bc497794cf4386d89c39a70a458e0139a9ed2"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+2/CImGui.v1.75.0.x86_64-apple-darwin14.tar.gz"
[[CImGui]]
arch = "armv7l"
git-tree-sha1 = "54f73235713103fb63dbf2deaf83423bf6e571ec"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "e000b44d7f804fa3bff1735344ee49cea7e3f940ac37802c7786a77d405da862"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.75.0+2/CImGui.v1.75.0.armv7l-linux-gnueabihf.tar.gz"
