[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "28572f685a9dfa4edc604c6375dfad63a5196411"
os = "freebsd"

    [[CImGui.download]]
    sha256 = "af2545eaa22de2d8d47975726ae91bf5dbdd479472705aef54aa88e5e1db2258"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+1/CImGui.v1.76.0.x86_64-unknown-freebsd11.1.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "361224f1ca271f96867a6527db8ad6961bcd4b58"
os = "windows"

    [[CImGui.download]]
    sha256 = "dfedb294dde76c1f700bbaa95783998b385fda790c41d2efffa60f25b1f6e41c"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+1/CImGui.v1.76.0.x86_64-w64-mingw32.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "ae0cf9e6a11438c56109f160a5f9e311973c9323"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "970e19a9c626af577cbf8d5d70bce4f1e19580d7fc379385e2fd3f8949c0fb94"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+1/CImGui.v1.76.0.x86_64-linux-gnu.tar.gz"
[[CImGui]]
arch = "armv7l"
git-tree-sha1 = "644a85a049ab5e112b281a96a54b5a46f8b80524"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "92c732fcab0e5ac0f35371da85dc8adbf259149122c9eddbb8e002234c334b24"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+1/CImGui.v1.76.0.armv7l-linux-musleabihf.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "c397531796a9dec98474e23d25a26d931b9784ef"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "382725341d088e209e092fc1982f98df44e5421c73a9440b99068a05882001ea"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+1/CImGui.v1.76.0.i686-linux-gnu.tar.gz"
[[CImGui]]
arch = "aarch64"
git-tree-sha1 = "48d4c8b7bad70fd6e50518954f5a89dcdd1db4b2"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "0e831c26aa6f89a5b789dd7e82529c9f6588778194dafc729a8049dce9025ba8"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+1/CImGui.v1.76.0.aarch64-linux-musl.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "34ae55ea1af55fee60039c9573e9e4b46601c6e6"
os = "windows"

    [[CImGui.download]]
    sha256 = "7d764ddfbbaac60654261b0931b090126c3fb3c35a996c147e17ac06f12f1387"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+1/CImGui.v1.76.0.i686-w64-mingw32.tar.gz"
[[CImGui]]
arch = "aarch64"
git-tree-sha1 = "63afa5e9dddfa9a5545a521988efe38839af3a73"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "115aa27a5660510f2c78967ddb2d982c5bcfd706eb2da9635ecca6be6ae61525"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+1/CImGui.v1.76.0.aarch64-linux-gnu.tar.gz"
[[CImGui]]
arch = "i686"
git-tree-sha1 = "78c6170341692fbbd12d1c1901dac8acefb72100"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "324d75d97b839503e3092d59566946a7837360734473b2235cd813027b16e56e"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+1/CImGui.v1.76.0.i686-linux-musl.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "faecb4b913e2990a0ff2dc8b9be89bd7686eb994"
libc = "musl"
os = "linux"

    [[CImGui.download]]
    sha256 = "70c28097219a44d08a72940184d2d1b07f86fa8a0696e43fabfd0ab88cb3e6bd"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+1/CImGui.v1.76.0.x86_64-linux-musl.tar.gz"
[[CImGui]]
arch = "powerpc64le"
git-tree-sha1 = "88a6886eab44889a50e5f5fb631f4d9315062960"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "55b3e31cb92da9a0df3401e38f59b1a20473d434a1da17973164cb3cf2117a89"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+1/CImGui.v1.76.0.powerpc64le-linux-gnu.tar.gz"
[[CImGui]]
arch = "x86_64"
git-tree-sha1 = "198a857cfd93a4e1d90d9b6b2c910722bf819111"
os = "macos"

    [[CImGui.download]]
    sha256 = "ecf962f20f74803e8ded87c31c544829e2cfae7d38c31c877d72adf63d2ade02"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+1/CImGui.v1.76.0.x86_64-apple-darwin14.tar.gz"
[[CImGui]]
arch = "armv7l"
git-tree-sha1 = "dbf25aa1316dc76776408c50596541c8b64c070a"
libc = "glibc"
os = "linux"

    [[CImGui.download]]
    sha256 = "ceca11b78fe78f2fb1c74be35f6082de78e5ec973ebda4f415b4d98e37981659"
    url = "https://github.com/JuliaBinaryWrappers/CImGui_jll.jl/releases/download/CImGui-v1.76.0+1/CImGui.v1.76.0.armv7l-linux-gnueabihf.tar.gz"
